# Generated by Django 5.1.3 on 2025-12-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('transaction_id', models.CharField(max_length=128)),
                ('alert_type', models.CharField(max_length=64)),
                ('materiality', models.FloatField()),
                ('amount', models.FloatField(null=True)),
                ('category', models.CharField(max_length=128, null=True)),
                ('vendor', models.CharField(max_length=256, null=True)),
            ],
            options={
            },
        ),
        migrations.CreateModel(
            name='AlertAssignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_id', models.IntegerField()),
                ('assigned_to', models.CharField(max_length=128)),
                ('assigned_at', models.DateTimeField()),
            ],
            options={
            },
        ),
        migrations.CreateModel(
            name='AlertComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=128, null=True)),
                ('comment', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField()),
                ('evidence_url', models.CharField(max_length=1024, null=True)),
            ],
            options={
            },
        ),
        migrations.CreateModel(
            name='AlertStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_id', models.IntegerField()),
                ('status', models.CharField(max_length=32)),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.CharField(max_length=128, null=True)),
            ],
            options={
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('token', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('role', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField()),
            ],
            options={
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=16, null=True)),
                ('category', models.CharField(max_length=128, null=True)),
                ('vendor', models.CharField(max_length=256, null=True)),
                ('has_po', models.BooleanField(null=True)),
                ('po_number', models.CharField(max_length=64, null=True)),
                ('user_id', models.CharField(max_length=128, null=True)),
                ('source', models.CharField(max_length=64, null=True)),
            ],
            options={
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContextProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('country', models.CharField(max_length=64)),
                ('region', models.CharField(max_length=64, null=True)),
                ('company_type', models.CharField(max_length=64)),
                ('sector', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=32)),
                ('currency', models.CharField(max_length=16)),
                ('systems', models.CharField(max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64, null=True)),
                ('sector', models.CharField(max_length=64, null=True)),
                ('title', models.CharField(max_length=256)),
                ('severity', models.FloatField(default=0.0)),
                ('source_url', models.CharField(max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegulatoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('regulation', models.CharField(max_length=128)),
                ('alert_type', models.CharField(max_length=64)),
                ('threshold_multiplier', models.FloatField(default=1.0)),
                ('description', models.CharField(max_length=512, null=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
