# Generated by Django 5.1.3 on 2025-12-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newssignal',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='newssignal',
            name='ai_summary',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='newssignal',
            name='suggested_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newssignal',
            name='validated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='newssignal',
            name='validated_by',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='ai_summary',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='suggested_by_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='validated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='validated_by',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
