# Generated by Django 5.1.3 on 2025-12-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_newssignal_ai_confidence_newssignal_ai_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64, null=True)),
                ('sector', models.CharField(max_length=64, null=True)),
                ('alert_type', models.CharField(max_length=64, null=True)),
                ('threshold_medium', models.FloatField(default=1000.0)),
                ('threshold_high', models.FloatField(default=10000.0)),
                ('days_low', models.IntegerField(default=7)),
                ('days_medium', models.IntegerField(default=3)),
                ('days_high', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
