# Generated by Django 5.1.3 on 2025-12-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_newssource_regulatorysource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('doc_type', models.CharField(max_length=64, null=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('country', models.CharField(max_length=64, null=True)),
                ('region', models.CharField(max_length=64, null=True)),
                ('company_type', models.CharField(max_length=64, null=True)),
                ('sector', models.CharField(max_length=64, null=True)),
                ('effective_date', models.DateField(null=True)),
                ('source_url', models.CharField(max_length=512, null=True)),
                ('suggested_by_ai', models.BooleanField(default=False)),
                ('ai_summary', models.CharField(max_length=1000, null=True)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('processed', models.BooleanField(default=False)),
                ('validated_by', models.CharField(max_length=128, null=True)),
                ('validated_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
