# Generated by Django 5.1.3 on 2026-01-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_contextdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('slack_webhook_url', models.CharField(blank=True, max_length=512, null=True)),
                ('teams_webhook_url', models.CharField(blank=True, max_length=512, null=True)),
                ('email_digest_list', models.CharField(blank=True, max_length=512, null=True)),
                ('auto_email_enabled', models.BooleanField(default=True)),
                ('auto_close_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
