# Generated by Django 5.1.3 on 2026-01-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_integrationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_id', models.IntegerField(null=True)),
                ('transaction_id', models.CharField(max_length=128, null=True)),
                ('user_id', models.CharField(max_length=128)),
                ('feedback_type', models.CharField(max_length=32)),
                ('comment', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
            },
        ),
        migrations.AddField(
            model_name='contextprofile',
            name='persona',
            field=models.CharField(default='Standard Auditor', max_length=64),
        ),
    ]
