# Generated by Django 5.1.3 on 2026-01-20 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_aifeedback_contextprofile_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(default='New', max_length=32)),
                ('priority', models.CharField(default='Medium', max_length=32)),
                ('assigned_to', models.CharField(max_length=128, null=True)),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditCaseComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dashboard.auditcase')),
            ],
        ),
    ]
