# Generated by Django 5.1.3 on 2026-01-20 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auditcase_auditcasecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditCaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=256)),
                ('file_url', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(max_length=128)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dashboard.auditcase')),
            ],
        ),
        migrations.CreateModel(
            name='RiskAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('conditions', models.JSONField()),
                ('action', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AlertAssignment',
        ),
        migrations.DeleteModel(
            name='AlertComment',
        ),
        migrations.DeleteModel(
            name='NewsSignal',
        ),
        migrations.DeleteModel(
            name='NewsSource',
        ),
        migrations.DeleteModel(
            name='SlaPolicy',
        ),
        migrations.DeleteModel(
            name='AlertStatus',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='aifeedback',
            options={},
        ),
        migrations.AlterModelOptions(
            name='apitoken',
            options={},
        ),
        migrations.RemoveField(
            model_name='alert',
            name='category',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='contextprofile',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='contextprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='contextprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contextprofile',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='contextprofile',
            name='region',
        ),
        migrations.RemoveField(
            model_name='contextprofile',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='contextprofile',
            name='size',
        ),
        migrations.RemoveField(
            model_name='contextprofile',
            name='systems',
        ),
        migrations.RemoveField(
            model_name='regulatoryrule',
            name='ai_summary',
        ),
        migrations.RemoveField(
            model_name='regulatoryrule',
            name='threshold_multiplier',
        ),
        migrations.RemoveField(
            model_name='regulatoryrule',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='regulatoryrule',
            name='validated_at',
        ),
        migrations.RemoveField(
            model_name='regulatoryrule',
            name='validated_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='has_po',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='source',
        ),
        migrations.AddField(
            model_name='alert',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(default='Medium', max_length=32),
        ),
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(default='New', max_length=32),
        ),
        migrations.AddField(
            model_name='alert',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.transaction'),
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='regulatoryrule',
            name='threshold_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='Pending', max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default='UNKNOWN_TX_ID', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='materiality',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='alert',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='vendor',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contextprofile',
            name='persona',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='regulatoryrule',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='BRL', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vendor',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterModelTable(
            name='alert',
            table=None,
        ),
        migrations.AlterModelTable(
            name='transaction',
            table=None,
        ),
    ]
