# Generated by Django 5.1.3 on 2026-01-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auditcaseattachment_riskagent_delete_alertassignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aifeedback',
            name='alert_id',
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='user_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='token',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='user_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterModelTable(
            name='aifeedback',
            table=None,
        ),
        migrations.AlterModelTable(
            name='apitoken',
            table=None,
        ),
    ]
