# Generated by Django 5.1.3 on 2026-01-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_aifeedback_alert_id_alter_aifeedback_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextprofile',
            name='user_id',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
