# Generated by Django 5.1.3 on 2026-01-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_contextprofile_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextdocument',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
