# Generated by Django 5.1.3 on 2026-01-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_contextdocument_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextprofile',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
