# Generated by Django 5.1.3 on 2026-01-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_contextprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditcase',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
