# Generated by Django 5.1.3 on 2026-01-21 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_externalsystem_ingestedsignal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, null=True)),
                ('value', models.CharField(max_length=256)),
                ('risk_factor', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.referencelist')),
            ],
        ),
    ]
