# Generated by Django 5.1.3 on 2026-01-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_referencelist_referenceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextprofile',
            name='department',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
