# Generated by Django 5.1.3 on 2026-01-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_contextprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextprofile',
            name='approval_limits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contextprofile',
            name='base_currency',
            field=models.CharField(default='BRL', max_length=10),
        ),
        migrations.AddField(
            model_name='contextprofile',
            name='org_structure',
            field=models.CharField(choices=[('Functional', 'Funcional'), ('Divisional', 'Divisional'), ('Matrix', 'Matricial'), ('SME', 'Pequena/Média Empresa')], default='Functional', max_length=32),
        ),
        migrations.AddField(
            model_name='contextprofile',
            name='sector',
            field=models.CharField(choices=[('Manufacturing', 'Manufatura'), ('Services', 'Serviços/Consultoria'), ('SaaS', 'Tecnologia (SaaS)'), ('Retail', 'Varejo'), ('Public', 'Setor Público'), ('Financial', 'Financeiro'), ('Other', 'Outros')], default='Other', max_length=32),
        ),
    ]
