# Generated by Django 5.1.3 on 2026-01-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_contextprofile_approval_limits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextdocument',
            name='embedding_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='contextdocument',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contextprofile',
            name='onboarding_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
