# Generated by Django 5.1.3 on 2026-01-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_contextdocument_embedding_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextdocument',
            name='embedding_vector',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
