# Generated by Django 5.1.3 on 2026-01-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_contextdocument_embedding_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='xai_explanation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
