# Generated by Django 5.1.3 on 2026-01-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_transaction_xai_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmutableAuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_id', models.CharField(max_length=128)),
                ('action_type', models.CharField(max_length=64)),
                ('resource_id', models.CharField(max_length=128)),
                ('details', models.JSONField(blank=True, null=True)),
                ('previous_hash', models.CharField(default='0', max_length=64)),
                ('current_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='ai_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='human_correction',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='input_context',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aifeedback',
            name='model_version',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
