# Generated by Django 5.1.3 on 2026-01-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_documentchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextdocument',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='contextdocument',
            name='scan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contextdocument',
            name='scan_status',
            field=models.CharField(default='Pending', max_length=32),
        ),
        migrations.AddField(
            model_name='contextdocument',
            name='uploaded_by',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
