# Generated by Django 5.1.3 on 2026-02-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_contextdocument_file_hash_contextdocument_scan_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditcaseattachment',
            name='file_url',
        ),
        migrations.AddField(
            model_name='auditcaseattachment',
            name='file',
            field=models.FileField(null=True, upload_to='case_attachments/'),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='active_learning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='integrationsettings',
            name='ai_sensitivity',
            field=models.FloatField(default=0.5),
        ),
        migrations.AlterField(
            model_name='auditcaseattachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
