# Generated by Django 5.1.3 on 2026-02-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_auditcaseattachment_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskagent',
            name='persona',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskagent',
            name='specialization',
            field=models.CharField(default='General', max_length=64),
        ),
    ]
