# Generated by Django 5.1.3 on 2026-02-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_riskagent_persona_riskagent_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskagent',
            name='reputation_score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='riskagent',
            name='training_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
