# Generated by Django 5.1.3 on 2026-02-07 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_riskagent_reputation_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('scanned_count', models.IntegerField(default=0)),
                ('finding_summary', models.TextField(blank=True, null=True)),
                ('finding_details', models.JSONField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.riskagent')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
