# Generated by Django 5.1.3 on 2026-02-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_riskagentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskagentlog',
            name='action_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskagentlog',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='riskagentlog',
            name='suggested_action',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
