# Generated by Django 5.1.3 on 2026-02-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_riskagentlog_action_taken_riskagentlog_risk_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGovernanceEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=64)),
                ('model_name', models.CharField(blank=True, max_length=128, null=True)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(default=0)),
                ('status', models.CharField(default='SUCCESS', max_length=32)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('was_corrected', models.BooleanField(default=False)),
                ('correction_details', models.JSONField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
