# Generated by Django 5.1.3 on 2026-02-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_aigovernanceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigovernanceevent',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
