# Generated by Django 5.1.3 on 2026-02-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_aigovernanceevent_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('model', models.CharField(choices=[('transaction', 'Transaction'), ('alert', 'Alert'), ('case', 'AuditCase')], default='transaction', max_length=32)),
                ('field', models.CharField(max_length=64)),
                ('operator', models.CharField(choices=[('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('==', '=='), ('!=', '!=')], default='>=', max_length=4)),
                ('value', models.CharField(max_length=128)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=32)),
                ('materiality', models.FloatField(default=0.5)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='auditcase',
            name='action_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='action_owner',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='finding_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='inherent_risk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditcase',
            name='residual_risk',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
