# Generated by Django 5.1.3 on 2026-06-03 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_contextprofile_compliance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalsystem',
            name='api_secret',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='auth_type',
            field=models.CharField(choices=[('API_KEY', 'Chave API'), ('OAUTH2', 'OAuth 2.0'), ('BASIC', 'Autenticação Básica'), ('BEARER', 'Token Bearer'), ('NONE', 'Sem Autenticação')], default='API_KEY', max_length=20),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='base_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='ingest_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='ingest_interval',
            field=models.IntegerField(default=300, help_text='Intervalo de ingestão em segundos'),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='last_ingest_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='oauth_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='oauth_client_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='oauth_client_secret',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='oauth_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='oauth_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='oauth_token_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='system_type',
            field=models.CharField(choices=[('ERP', 'Sistema ERP'), ('CRM', 'Sistema CRM'), ('DATABASE', 'Banco de Dados'), ('DOCUMENT', 'Sistema de Documentos'), ('HR', 'Sistema RH'), ('FINANCE', 'Sistema Financeiro'), ('CUSTOM', 'Sistema Customizado')], default='CUSTOM', max_length=32),
        ),
        migrations.AddField(
            model_name='externalsystem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='externalsystem',
            name='api_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='externalsystem',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=128)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('SUCCESS', 'Sucesso'), ('FAILED', 'Falha'), ('RETRYING', 'Tentando Novamente')], default='PENDING', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.externalsystem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
