# Generated by Django 5.1.3 on 2026-06-03 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_externalsystem_api_secret_externalsystem_auth_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalActionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('webhook', 'Webhook'), ('api_rest', 'REST API'), ('jira_ticket', 'Jira Ticket'), ('slack_message', 'Slack Message'), ('email', 'Email'), ('custom', 'Custom Action')], default='webhook', max_length=32)),
                ('endpoint_url', models.URLField(blank=True, max_length=512, null=True)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='POST', max_length=10)),
                ('payload_template', models.JSONField(blank=True, null=True)),
                ('headers', models.JSONField(blank=True, null=True)),
                ('auth_type', models.CharField(blank=True, choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('oauth2', 'OAuth2')], max_length=32, null=True)),
                ('auth_credentials', models.JSONField(blank=True, null=True)),
                ('jira_project_key', models.CharField(blank=True, max_length=64, null=True)),
                ('jira_issue_type', models.CharField(blank=True, default='Task', max_length=64, null=True)),
                ('email_recipients', models.CharField(blank=True, max_length=512, null=True)),
                ('email_subject_template', models.CharField(blank=True, max_length=256, null=True)),
                ('email_body_template', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.externalsystem')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalActionExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=32)),
                ('endpoint_url', models.URLField(blank=True, max_length=512, null=True)),
                ('payload_sent', models.JSONField(blank=True, null=True)),
                ('response_received', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.riskagent')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.alert')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.auditcase')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.transaction')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.externalactiontemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
