# Generated by Django 5.1.3 on 2026-06-04 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_externalactiontemplate_externalactionexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskagent',
            name='external_action_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.externalactiontemplate'),
        ),
    ]
