# Generated by Django 6.1.1 on 2026-09-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_excelstudio_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('question', models.TextField(blank=True)),
                ('answer_excerpt', models.TextField(blank=True)),
                ('mode', models.CharField(blank=True, max_length=10)),
                ('page', models.CharField(blank=True, max_length=60)),
                ('comment', models.TextField(blank=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='dashboard_cpf_created_idx'), models.Index(fields=['rating'], name='dashboard_cpf_rating_idx')],
            },
        ),
    ]
