# Generated by Django 6.1.1 on 2026-09-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_copilotfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotDigest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(default='daily', max_length=10)),
                ('day', models.DateField()),
                ('payload', models.JSONField(default=dict)),
                ('signals_count', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('recipients', models.TextField(blank=True)),
                ('status', models.CharField(default='stored', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='dashboard_cpd_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('period', 'day'), name='dashboard_digest_period_day_uq')],
            },
        ),
    ]
