# Generated by Django 6.1.2 on 2026-10-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_copilotdigest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(db_index=True, max_length=128)),
                ('kind', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Informação'), ('success', 'Sucesso'), ('warn', 'Aviso'), ('critical', 'Crítico')], default='info', max_length=16)),
                ('title', models.CharField(max_length=220)),
                ('body', models.TextField(blank=True, default='')),
                ('route', models.CharField(blank=True, default='', max_length=200)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='dashboard_notif_recipient_idx')],
            },
        ),
    ]
